// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// MockStockMovementRepository is an autogenerated mock type for the StockMovementRepository type
type MockStockMovementRepository struct {
	mock.Mock
}

type MockStockMovementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockMovementRepository) EXPECT() *MockStockMovementRepository_Expecter {
	return &MockStockMovementRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: sm
func (_m *MockStockMovementRepository) Create(sm *models.StockMovement) error {
	ret := _m.Called(sm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.StockMovement) error); ok {
		r0 = rf(sm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockMovementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockMovementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - sm *models.StockMovement
func (_e *MockStockMovementRepository_Expecter) Create(sm interface{}) *MockStockMovementRepository_Create_Call {
	return &MockStockMovementRepository_Create_Call{Call: _e.mock.On("Create", sm)}
}

func (_c *MockStockMovementRepository_Create_Call) Run(run func(sm *models.StockMovement)) *MockStockMovementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.StockMovement))
	})
	return _c
}

func (_c *MockStockMovementRepository_Create_Call) Return(_a0 error) *MockStockMovementRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockMovementRepository_Create_Call) RunAndReturn(run func(*models.StockMovement) error) *MockStockMovementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function with given fields: tx, sm
func (_m *MockStockMovementRepository) CreateWithTx(tx *gorm.DB, sm *models.StockMovement) error {
	ret := _m.Called(tx, sm)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.StockMovement) error); ok {
		r0 = rf(tx, sm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockMovementRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockStockMovementRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - sm *models.StockMovement
func (_e *MockStockMovementRepository_Expecter) CreateWithTx(tx interface{}, sm interface{}) *MockStockMovementRepository_CreateWithTx_Call {
	return &MockStockMovementRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", tx, sm)}
}

func (_c *MockStockMovementRepository_CreateWithTx_Call) Run(run func(tx *gorm.DB, sm *models.StockMovement)) *MockStockMovementRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.StockMovement))
	})
	return _c
}

func (_c *MockStockMovementRepository_CreateWithTx_Call) Return(_a0 error) *MockStockMovementRepository_CreateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockMovementRepository_CreateWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.StockMovement) error) *MockStockMovementRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchAndProduct provides a mock function with given fields: branchID, productID, offset, limit
func (_m *MockStockMovementRepository) FindByBranchAndProduct(branchID uuid.UUID, productID uuid.UUID, offset int, limit int) ([]models.StockMovement, int64, error) {
	ret := _m.Called(branchID, productID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchAndProduct")
	}

	var r0 []models.StockMovement
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, int, int) ([]models.StockMovement, int64, error)); ok {
		return rf(branchID, productID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, int, int) []models.StockMovement); ok {
		r0 = rf(branchID, productID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.StockMovement)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, productID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, productID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStockMovementRepository_FindByBranchAndProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchAndProduct'
type MockStockMovementRepository_FindByBranchAndProduct_Call struct {
	*mock.Call
}

// FindByBranchAndProduct is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - productID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockStockMovementRepository_Expecter) FindByBranchAndProduct(branchID interface{}, productID interface{}, offset interface{}, limit interface{}) *MockStockMovementRepository_FindByBranchAndProduct_Call {
	return &MockStockMovementRepository_FindByBranchAndProduct_Call{Call: _e.mock.On("FindByBranchAndProduct", branchID, productID, offset, limit)}
}

func (_c *MockStockMovementRepository_FindByBranchAndProduct_Call) Run(run func(branchID uuid.UUID, productID uuid.UUID, offset int, limit int)) *MockStockMovementRepository_FindByBranchAndProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockStockMovementRepository_FindByBranchAndProduct_Call) Return(_a0 []models.StockMovement, _a1 int64, _a2 error) *MockStockMovementRepository_FindByBranchAndProduct_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStockMovementRepository_FindByBranchAndProduct_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, int, int) ([]models.StockMovement, int64, error)) *MockStockMovementRepository_FindByBranchAndProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockMovementRepository creates a new instance of MockStockMovementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockMovementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockMovementRepository {
	mock := &MockStockMovementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
