// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStylistRepository is an autogenerated mock type for the StylistRepository type
type MockStylistRepository struct {
	mock.Mock
}

type MockStylistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStylistRepository) EXPECT() *MockStylistRepository_Expecter {
	return &MockStylistRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: stylist
func (_m *MockStylistRepository) Create(stylist *models.Stylist) error {
	ret := _m.Called(stylist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Stylist) error); ok {
		r0 = rf(stylist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStylistRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStylistRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - stylist *models.Stylist
func (_e *MockStylistRepository_Expecter) Create(stylist interface{}) *MockStylistRepository_Create_Call {
	return &MockStylistRepository_Create_Call{Call: _e.mock.On("Create", stylist)}
}

func (_c *MockStylistRepository_Create_Call) Run(run func(stylist *models.Stylist)) *MockStylistRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Stylist))
	})
	return _c
}

func (_c *MockStylistRepository_Create_Call) Return(_a0 error) *MockStylistRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStylistRepository_Create_Call) RunAndReturn(run func(*models.Stylist) error) *MockStylistRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockStylistRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStylistRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStylistRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockStylistRepository_Expecter) Delete(id interface{}) *MockStylistRepository_Delete_Call {
	return &MockStylistRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockStylistRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockStylistRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockStylistRepository_Delete_Call) Return(_a0 error) *MockStylistRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStylistRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockStylistRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockStylistRepository) FindAll(offset int, limit int) ([]models.Stylist, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Stylist
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Stylist, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Stylist); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Stylist)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStylistRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockStylistRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockStylistRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockStylistRepository_FindAll_Call {
	return &MockStylistRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockStylistRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockStylistRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockStylistRepository_FindAll_Call) Return(_a0 []models.Stylist, _a1 int64, _a2 error) *MockStylistRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStylistRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.Stylist, int64, error)) *MockStylistRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockStylistRepository) FindByID(id uuid.UUID) (*models.Stylist, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Stylist
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Stylist, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Stylist); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stylist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStylistRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockStylistRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockStylistRepository_Expecter) FindByID(id interface{}) *MockStylistRepository_FindByID_Call {
	return &MockStylistRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockStylistRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockStylistRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockStylistRepository_FindByID_Call) Return(_a0 *models.Stylist, _a1 error) *MockStylistRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStylistRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Stylist, error)) *MockStylistRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: stylist
func (_m *MockStylistRepository) Update(stylist *models.Stylist) error {
	ret := _m.Called(stylist)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Stylist) error); ok {
		r0 = rf(stylist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStylistRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStylistRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - stylist *models.Stylist
func (_e *MockStylistRepository_Expecter) Update(stylist interface{}) *MockStylistRepository_Update_Call {
	return &MockStylistRepository_Update_Call{Call: _e.mock.On("Update", stylist)}
}

func (_c *MockStylistRepository_Update_Call) Run(run func(stylist *models.Stylist)) *MockStylistRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Stylist))
	})
	return _c
}

func (_c *MockStylistRepository_Update_Call) Return(_a0 error) *MockStylistRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStylistRepository_Update_Call) RunAndReturn(run func(*models.Stylist) error) *MockStylistRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStylistRepository creates a new instance of MockStylistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStylistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStylistRepository {
	mock := &MockStylistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
