// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// CountTodayByBranch provides a mock function with given fields: branchID
func (_m *MockTransactionRepository) CountTodayByBranch(branchID uuid.UUID) (int64, error) {
	ret := _m.Called(branchID)

	if len(ret) == 0 {
		panic("no return value specified for CountTodayByBranch")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (int64, error)); ok {
		return rf(branchID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) int64); ok {
		r0 = rf(branchID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_CountTodayByBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTodayByBranch'
type MockTransactionRepository_CountTodayByBranch_Call struct {
	*mock.Call
}

// CountTodayByBranch is a helper method to define mock.On call
//   - branchID uuid.UUID
func (_e *MockTransactionRepository_Expecter) CountTodayByBranch(branchID interface{}) *MockTransactionRepository_CountTodayByBranch_Call {
	return &MockTransactionRepository_CountTodayByBranch_Call{Call: _e.mock.On("CountTodayByBranch", branchID)}
}

func (_c *MockTransactionRepository_CountTodayByBranch_Call) Run(run func(branchID uuid.UUID)) *MockTransactionRepository_CountTodayByBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_CountTodayByBranch_Call) Return(_a0 int64, _a1 error) *MockTransactionRepository_CountTodayByBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_CountTodayByBranch_Call) RunAndReturn(run func(uuid.UUID) (int64, error)) *MockTransactionRepository_CountTodayByBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItemWithTx provides a mock function with given fields: tx, item
func (_m *MockTransactionRepository) CreateItemWithTx(tx *gorm.DB, item *models.TransactionItem) error {
	ret := _m.Called(tx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItemWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.TransactionItem) error); ok {
		r0 = rf(tx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_CreateItemWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItemWithTx'
type MockTransactionRepository_CreateItemWithTx_Call struct {
	*mock.Call
}

// CreateItemWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - item *models.TransactionItem
func (_e *MockTransactionRepository_Expecter) CreateItemWithTx(tx interface{}, item interface{}) *MockTransactionRepository_CreateItemWithTx_Call {
	return &MockTransactionRepository_CreateItemWithTx_Call{Call: _e.mock.On("CreateItemWithTx", tx, item)}
}

func (_c *MockTransactionRepository_CreateItemWithTx_Call) Run(run func(tx *gorm.DB, item *models.TransactionItem)) *MockTransactionRepository_CreateItemWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.TransactionItem))
	})
	return _c
}

func (_c *MockTransactionRepository_CreateItemWithTx_Call) Return(_a0 error) *MockTransactionRepository_CreateItemWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_CreateItemWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.TransactionItem) error) *MockTransactionRepository_CreateItemWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentWithTx provides a mock function with given fields: tx, payment
func (_m *MockTransactionRepository) CreatePaymentWithTx(tx *gorm.DB, payment *models.Payment) error {
	ret := _m.Called(tx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.Payment) error); ok {
		r0 = rf(tx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_CreatePaymentWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentWithTx'
type MockTransactionRepository_CreatePaymentWithTx_Call struct {
	*mock.Call
}

// CreatePaymentWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - payment *models.Payment
func (_e *MockTransactionRepository_Expecter) CreatePaymentWithTx(tx interface{}, payment interface{}) *MockTransactionRepository_CreatePaymentWithTx_Call {
	return &MockTransactionRepository_CreatePaymentWithTx_Call{Call: _e.mock.On("CreatePaymentWithTx", tx, payment)}
}

func (_c *MockTransactionRepository_CreatePaymentWithTx_Call) Run(run func(tx *gorm.DB, payment *models.Payment)) *MockTransactionRepository_CreatePaymentWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.Payment))
	})
	return _c
}

func (_c *MockTransactionRepository_CreatePaymentWithTx_Call) Return(_a0 error) *MockTransactionRepository_CreatePaymentWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_CreatePaymentWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.Payment) error) *MockTransactionRepository_CreatePaymentWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function with given fields: tx, txn
func (_m *MockTransactionRepository) CreateWithTx(tx *gorm.DB, txn *models.Transaction) error {
	ret := _m.Called(tx, txn)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.Transaction) error); ok {
		r0 = rf(tx, txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockTransactionRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - txn *models.Transaction
func (_e *MockTransactionRepository_Expecter) CreateWithTx(tx interface{}, txn interface{}) *MockTransactionRepository_CreateWithTx_Call {
	return &MockTransactionRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", tx, txn)}
}

func (_c *MockTransactionRepository_CreateWithTx_Call) Run(run func(tx *gorm.DB, txn *models.Transaction)) *MockTransactionRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_CreateWithTx_Call) Return(_a0 error) *MockTransactionRepository_CreateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_CreateWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.Transaction) error) *MockTransactionRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function with no fields
func (_m *MockTransactionRepository) DB() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockTransactionRepository_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockTransactionRepository_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockTransactionRepository_Expecter) DB() *MockTransactionRepository_DB_Call {
	return &MockTransactionRepository_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockTransactionRepository_DB_Call) Run(run func()) *MockTransactionRepository_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionRepository_DB_Call) Return(_a0 *gorm.DB) *MockTransactionRepository_DB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_DB_Call) RunAndReturn(run func() *gorm.DB) *MockTransactionRepository_DB_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchID provides a mock function with given fields: branchID, offset, limit
func (_m *MockTransactionRepository) FindByBranchID(branchID uuid.UUID, offset int, limit int) ([]models.Transaction, int64, error) {
	ret := _m.Called(branchID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchID")
	}

	var r0 []models.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.Transaction, int64, error)); ok {
		return rf(branchID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.Transaction); ok {
		r0 = rf(branchID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionRepository_FindByBranchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchID'
type MockTransactionRepository_FindByBranchID_Call struct {
	*mock.Call
}

// FindByBranchID is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockTransactionRepository_Expecter) FindByBranchID(branchID interface{}, offset interface{}, limit interface{}) *MockTransactionRepository_FindByBranchID_Call {
	return &MockTransactionRepository_FindByBranchID_Call{Call: _e.mock.On("FindByBranchID", branchID, offset, limit)}
}

func (_c *MockTransactionRepository_FindByBranchID_Call) Run(run func(branchID uuid.UUID, offset int, limit int)) *MockTransactionRepository_FindByBranchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByBranchID_Call) Return(_a0 []models.Transaction, _a1 int64, _a2 error) *MockTransactionRepository_FindByBranchID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransactionRepository_FindByBranchID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.Transaction, int64, error)) *MockTransactionRepository_FindByBranchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDrawerID provides a mock function with given fields: drawerID
func (_m *MockTransactionRepository) FindByDrawerID(drawerID uuid.UUID) ([]models.Transaction, error) {
	ret := _m.Called(drawerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByDrawerID")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Transaction, error)); ok {
		return rf(drawerID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Transaction); ok {
		r0 = rf(drawerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(drawerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByDrawerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDrawerID'
type MockTransactionRepository_FindByDrawerID_Call struct {
	*mock.Call
}

// FindByDrawerID is a helper method to define mock.On call
//   - drawerID uuid.UUID
func (_e *MockTransactionRepository_Expecter) FindByDrawerID(drawerID interface{}) *MockTransactionRepository_FindByDrawerID_Call {
	return &MockTransactionRepository_FindByDrawerID_Call{Call: _e.mock.On("FindByDrawerID", drawerID)}
}

func (_c *MockTransactionRepository_FindByDrawerID_Call) Run(run func(drawerID uuid.UUID)) *MockTransactionRepository_FindByDrawerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByDrawerID_Call) Return(_a0 []models.Transaction, _a1 error) *MockTransactionRepository_FindByDrawerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByDrawerID_Call) RunAndReturn(run func(uuid.UUID) ([]models.Transaction, error)) *MockTransactionRepository_FindByDrawerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockTransactionRepository) FindByID(id uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) FindByID(id interface{}) *MockTransactionRepository_FindByID_Call {
	return &MockTransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockTransactionRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) Return(_a0 *models.Transaction, _a1 error) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Transaction, error)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdempotencyKey provides a mock function with given fields: key
func (_m *MockTransactionRepository) FindByIdempotencyKey(key string) (*models.Transaction, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdempotencyKey")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Transaction, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Transaction); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdempotencyKey'
type MockTransactionRepository_FindByIdempotencyKey_Call struct {
	*mock.Call
}

// FindByIdempotencyKey is a helper method to define mock.On call
//   - key string
func (_e *MockTransactionRepository_Expecter) FindByIdempotencyKey(key interface{}) *MockTransactionRepository_FindByIdempotencyKey_Call {
	return &MockTransactionRepository_FindByIdempotencyKey_Call{Call: _e.mock.On("FindByIdempotencyKey", key)}
}

func (_c *MockTransactionRepository_FindByIdempotencyKey_Call) Run(run func(key string)) *MockTransactionRepository_FindByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByIdempotencyKey_Call) Return(_a0 *models.Transaction, _a1 error) *MockTransactionRepository_FindByIdempotencyKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByIdempotencyKey_Call) RunAndReturn(run func(string) (*models.Transaction, error)) *MockTransactionRepository_FindByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetStylistCommissionSummary provides a mock function with given fields: stylistID, branchID, month, year
func (_m *MockTransactionRepository) GetStylistCommissionSummary(stylistID uuid.UUID, branchID uuid.UUID, month int, year int) (int64, int64, error) {
	ret := _m.Called(stylistID, branchID, month, year)

	if len(ret) == 0 {
		panic("no return value specified for GetStylistCommissionSummary")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, int, int) (int64, int64, error)); ok {
		return rf(stylistID, branchID, month, year)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, int, int) int64); ok {
		r0 = rf(stylistID, branchID, month, year)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, int, int) int64); ok {
		r1 = rf(stylistID, branchID, month, year)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = rf(stylistID, branchID, month, year)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionRepository_GetStylistCommissionSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStylistCommissionSummary'
type MockTransactionRepository_GetStylistCommissionSummary_Call struct {
	*mock.Call
}

// GetStylistCommissionSummary is a helper method to define mock.On call
//   - stylistID uuid.UUID
//   - branchID uuid.UUID
//   - month int
//   - year int
func (_e *MockTransactionRepository_Expecter) GetStylistCommissionSummary(stylistID interface{}, branchID interface{}, month interface{}, year interface{}) *MockTransactionRepository_GetStylistCommissionSummary_Call {
	return &MockTransactionRepository_GetStylistCommissionSummary_Call{Call: _e.mock.On("GetStylistCommissionSummary", stylistID, branchID, month, year)}
}

func (_c *MockTransactionRepository_GetStylistCommissionSummary_Call) Run(run func(stylistID uuid.UUID, branchID uuid.UUID, month int, year int)) *MockTransactionRepository_GetStylistCommissionSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTransactionRepository_GetStylistCommissionSummary_Call) Return(totalSales int64, totalCommission int64, err error) *MockTransactionRepository_GetStylistCommissionSummary_Call {
	_c.Call.Return(totalSales, totalCommission, err)
	return _c
}

func (_c *MockTransactionRepository_GetStylistCommissionSummary_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, int, int) (int64, int64, error)) *MockTransactionRepository_GetStylistCommissionSummary_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: txn
func (_m *MockTransactionRepository) Update(txn *models.Transaction) error {
	ret := _m.Called(txn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - txn *models.Transaction
func (_e *MockTransactionRepository_Expecter) Update(txn interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", txn)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(txn *models.Transaction)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(_a0 error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(*models.Transaction) error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function with given fields: tx, txn
func (_m *MockTransactionRepository) UpdateWithTx(tx *gorm.DB, txn *models.Transaction) error {
	ret := _m.Called(tx, txn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.Transaction) error); ok {
		r0 = rf(tx, txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockTransactionRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - txn *models.Transaction
func (_e *MockTransactionRepository_Expecter) UpdateWithTx(tx interface{}, txn interface{}) *MockTransactionRepository_UpdateWithTx_Call {
	return &MockTransactionRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", tx, txn)}
}

func (_c *MockTransactionRepository_UpdateWithTx_Call) Run(run func(tx *gorm.DB, txn *models.Transaction)) *MockTransactionRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateWithTx_Call) Return(_a0 error) *MockTransactionRepository_UpdateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_UpdateWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.Transaction) error) *MockTransactionRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
