// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: product
func (_m *MockProductRepository) Create(product *models.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *models.Product
func (_e *MockProductRepository_Expecter) Create(product interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(product *models.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Product))
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(_a0 error) *MockProductRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(*models.Product) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) Delete(id interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(_a0 error) *MockProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockProductRepository) FindAll(offset int, limit int) ([]models.Product, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Product
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Product, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Product); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockProductRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockProductRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockProductRepository_FindAll_Call {
	return &MockProductRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockProductRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockProductRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepository_FindAll_Call) Return(_a0 []models.Product, _a1 int64, _a2 error) *MockProductRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.Product, int64, error)) *MockProductRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockProductRepository) FindByID(id uuid.UUID) (*models.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) FindByID(id interface{}) *MockProductRepository_FindByID_Call {
	return &MockProductRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockProductRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockProductRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_FindByID_Call) Return(_a0 *models.Product, _a1 error) *MockProductRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Product, error)) *MockProductRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: product
func (_m *MockProductRepository) Update(product *models.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *models.Product
func (_e *MockProductRepository_Expecter) Update(product interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(product *models.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Product))
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(_a0 error) *MockProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(*models.Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
