// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// MockBranchProductRepository is an autogenerated mock type for the BranchProductRepository type
type MockBranchProductRepository struct {
	mock.Mock
}

type MockBranchProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBranchProductRepository) EXPECT() *MockBranchProductRepository_Expecter {
	return &MockBranchProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: bp
func (_m *MockBranchProductRepository) Create(bp *models.BranchProduct) error {
	ret := _m.Called(bp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BranchProduct) error); ok {
		r0 = rf(bp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBranchProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - bp *models.BranchProduct
func (_e *MockBranchProductRepository_Expecter) Create(bp interface{}) *MockBranchProductRepository_Create_Call {
	return &MockBranchProductRepository_Create_Call{Call: _e.mock.On("Create", bp)}
}

func (_c *MockBranchProductRepository_Create_Call) Run(run func(bp *models.BranchProduct)) *MockBranchProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.BranchProduct))
	})
	return _c
}

func (_c *MockBranchProductRepository_Create_Call) Return(_a0 error) *MockBranchProductRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchProductRepository_Create_Call) RunAndReturn(run func(*models.BranchProduct) error) *MockBranchProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockBranchProductRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBranchProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBranchProductRepository_Expecter) Delete(id interface{}) *MockBranchProductRepository_Delete_Call {
	return &MockBranchProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockBranchProductRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockBranchProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchProductRepository_Delete_Call) Return(_a0 error) *MockBranchProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchProductRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockBranchProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchAndProduct provides a mock function with given fields: branchID, productID
func (_m *MockBranchProductRepository) FindByBranchAndProduct(branchID uuid.UUID, productID uuid.UUID) (*models.BranchProduct, error) {
	ret := _m.Called(branchID, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchAndProduct")
	}

	var r0 *models.BranchProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.BranchProduct, error)); ok {
		return rf(branchID, productID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.BranchProduct); ok {
		r0 = rf(branchID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BranchProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(branchID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchProductRepository_FindByBranchAndProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchAndProduct'
type MockBranchProductRepository_FindByBranchAndProduct_Call struct {
	*mock.Call
}

// FindByBranchAndProduct is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - productID uuid.UUID
func (_e *MockBranchProductRepository_Expecter) FindByBranchAndProduct(branchID interface{}, productID interface{}) *MockBranchProductRepository_FindByBranchAndProduct_Call {
	return &MockBranchProductRepository_FindByBranchAndProduct_Call{Call: _e.mock.On("FindByBranchAndProduct", branchID, productID)}
}

func (_c *MockBranchProductRepository_FindByBranchAndProduct_Call) Run(run func(branchID uuid.UUID, productID uuid.UUID)) *MockBranchProductRepository_FindByBranchAndProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchProductRepository_FindByBranchAndProduct_Call) Return(_a0 *models.BranchProduct, _a1 error) *MockBranchProductRepository_FindByBranchAndProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchProductRepository_FindByBranchAndProduct_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*models.BranchProduct, error)) *MockBranchProductRepository_FindByBranchAndProduct_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchAndProductForUpdate provides a mock function with given fields: tx, branchID, productID
func (_m *MockBranchProductRepository) FindByBranchAndProductForUpdate(tx *gorm.DB, branchID uuid.UUID, productID uuid.UUID) (*models.BranchProduct, error) {
	ret := _m.Called(tx, branchID, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchAndProductForUpdate")
	}

	var r0 *models.BranchProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID, uuid.UUID) (*models.BranchProduct, error)); ok {
		return rf(tx, branchID, productID)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID, uuid.UUID) *models.BranchProduct); ok {
		r0 = rf(tx, branchID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BranchProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(tx, branchID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchProductRepository_FindByBranchAndProductForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchAndProductForUpdate'
type MockBranchProductRepository_FindByBranchAndProductForUpdate_Call struct {
	*mock.Call
}

// FindByBranchAndProductForUpdate is a helper method to define mock.On call
//   - tx *gorm.DB
//   - branchID uuid.UUID
//   - productID uuid.UUID
func (_e *MockBranchProductRepository_Expecter) FindByBranchAndProductForUpdate(tx interface{}, branchID interface{}, productID interface{}) *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call {
	return &MockBranchProductRepository_FindByBranchAndProductForUpdate_Call{Call: _e.mock.On("FindByBranchAndProductForUpdate", tx, branchID, productID)}
}

func (_c *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call) Run(run func(tx *gorm.DB, branchID uuid.UUID, productID uuid.UUID)) *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call) Return(_a0 *models.BranchProduct, _a1 error) *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call) RunAndReturn(run func(*gorm.DB, uuid.UUID, uuid.UUID) (*models.BranchProduct, error)) *MockBranchProductRepository_FindByBranchAndProductForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchID provides a mock function with given fields: branchID, offset, limit
func (_m *MockBranchProductRepository) FindByBranchID(branchID uuid.UUID, offset int, limit int) ([]models.BranchProduct, int64, error) {
	ret := _m.Called(branchID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchID")
	}

	var r0 []models.BranchProduct
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.BranchProduct, int64, error)); ok {
		return rf(branchID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.BranchProduct); ok {
		r0 = rf(branchID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BranchProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBranchProductRepository_FindByBranchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchID'
type MockBranchProductRepository_FindByBranchID_Call struct {
	*mock.Call
}

// FindByBranchID is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockBranchProductRepository_Expecter) FindByBranchID(branchID interface{}, offset interface{}, limit interface{}) *MockBranchProductRepository_FindByBranchID_Call {
	return &MockBranchProductRepository_FindByBranchID_Call{Call: _e.mock.On("FindByBranchID", branchID, offset, limit)}
}

func (_c *MockBranchProductRepository_FindByBranchID_Call) Run(run func(branchID uuid.UUID, offset int, limit int)) *MockBranchProductRepository_FindByBranchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockBranchProductRepository_FindByBranchID_Call) Return(_a0 []models.BranchProduct, _a1 int64, _a2 error) *MockBranchProductRepository_FindByBranchID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBranchProductRepository_FindByBranchID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.BranchProduct, int64, error)) *MockBranchProductRepository_FindByBranchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockBranchProductRepository) FindByID(id uuid.UUID) (*models.BranchProduct, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.BranchProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.BranchProduct, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.BranchProduct); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BranchProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchProductRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBranchProductRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBranchProductRepository_Expecter) FindByID(id interface{}) *MockBranchProductRepository_FindByID_Call {
	return &MockBranchProductRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockBranchProductRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockBranchProductRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchProductRepository_FindByID_Call) Return(_a0 *models.BranchProduct, _a1 error) *MockBranchProductRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchProductRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.BranchProduct, error)) *MockBranchProductRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: bp
func (_m *MockBranchProductRepository) Update(bp *models.BranchProduct) error {
	ret := _m.Called(bp)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BranchProduct) error); ok {
		r0 = rf(bp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBranchProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - bp *models.BranchProduct
func (_e *MockBranchProductRepository_Expecter) Update(bp interface{}) *MockBranchProductRepository_Update_Call {
	return &MockBranchProductRepository_Update_Call{Call: _e.mock.On("Update", bp)}
}

func (_c *MockBranchProductRepository_Update_Call) Run(run func(bp *models.BranchProduct)) *MockBranchProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.BranchProduct))
	})
	return _c
}

func (_c *MockBranchProductRepository_Update_Call) Return(_a0 error) *MockBranchProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchProductRepository_Update_Call) RunAndReturn(run func(*models.BranchProduct) error) *MockBranchProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function with given fields: tx, bp
func (_m *MockBranchProductRepository) UpdateWithTx(tx *gorm.DB, bp *models.BranchProduct) error {
	ret := _m.Called(tx, bp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.BranchProduct) error); ok {
		r0 = rf(tx, bp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchProductRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockBranchProductRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - bp *models.BranchProduct
func (_e *MockBranchProductRepository_Expecter) UpdateWithTx(tx interface{}, bp interface{}) *MockBranchProductRepository_UpdateWithTx_Call {
	return &MockBranchProductRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", tx, bp)}
}

func (_c *MockBranchProductRepository_UpdateWithTx_Call) Run(run func(tx *gorm.DB, bp *models.BranchProduct)) *MockBranchProductRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.BranchProduct))
	})
	return _c
}

func (_c *MockBranchProductRepository_UpdateWithTx_Call) Return(_a0 error) *MockBranchProductRepository_UpdateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchProductRepository_UpdateWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.BranchProduct) error) *MockBranchProductRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBranchProductRepository creates a new instance of MockBranchProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBranchProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBranchProductRepository {
	mock := &MockBranchProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
