// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSalaryRepository is an autogenerated mock type for the SalaryRepository type
type MockSalaryRepository struct {
	mock.Mock
}

type MockSalaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSalaryRepository) EXPECT() *MockSalaryRepository_Expecter {
	return &MockSalaryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: salary
func (_m *MockSalaryRepository) Create(salary *models.SalaryRecord) error {
	ret := _m.Called(salary)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SalaryRecord) error); ok {
		r0 = rf(salary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSalaryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSalaryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - salary *models.SalaryRecord
func (_e *MockSalaryRepository_Expecter) Create(salary interface{}) *MockSalaryRepository_Create_Call {
	return &MockSalaryRepository_Create_Call{Call: _e.mock.On("Create", salary)}
}

func (_c *MockSalaryRepository_Create_Call) Run(run func(salary *models.SalaryRecord)) *MockSalaryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.SalaryRecord))
	})
	return _c
}

func (_c *MockSalaryRepository_Create_Call) Return(_a0 error) *MockSalaryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSalaryRepository_Create_Call) RunAndReturn(run func(*models.SalaryRecord) error) *MockSalaryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranch provides a mock function with given fields: branchID, offset, limit
func (_m *MockSalaryRepository) FindByBranch(branchID uuid.UUID, offset int, limit int) ([]models.SalaryRecord, int64, error) {
	ret := _m.Called(branchID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranch")
	}

	var r0 []models.SalaryRecord
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.SalaryRecord, int64, error)); ok {
		return rf(branchID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.SalaryRecord); ok {
		r0 = rf(branchID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SalaryRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSalaryRepository_FindByBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranch'
type MockSalaryRepository_FindByBranch_Call struct {
	*mock.Call
}

// FindByBranch is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockSalaryRepository_Expecter) FindByBranch(branchID interface{}, offset interface{}, limit interface{}) *MockSalaryRepository_FindByBranch_Call {
	return &MockSalaryRepository_FindByBranch_Call{Call: _e.mock.On("FindByBranch", branchID, offset, limit)}
}

func (_c *MockSalaryRepository_FindByBranch_Call) Run(run func(branchID uuid.UUID, offset int, limit int)) *MockSalaryRepository_FindByBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockSalaryRepository_FindByBranch_Call) Return(_a0 []models.SalaryRecord, _a1 int64, _a2 error) *MockSalaryRepository_FindByBranch_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSalaryRepository_FindByBranch_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.SalaryRecord, int64, error)) *MockSalaryRepository_FindByBranch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockSalaryRepository) FindByID(id uuid.UUID) (*models.SalaryRecord, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.SalaryRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.SalaryRecord, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.SalaryRecord); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SalaryRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSalaryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSalaryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockSalaryRepository_Expecter) FindByID(id interface{}) *MockSalaryRepository_FindByID_Call {
	return &MockSalaryRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockSalaryRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockSalaryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockSalaryRepository_FindByID_Call) Return(_a0 *models.SalaryRecord, _a1 error) *MockSalaryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSalaryRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.SalaryRecord, error)) *MockSalaryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: salary
func (_m *MockSalaryRepository) Update(salary *models.SalaryRecord) error {
	ret := _m.Called(salary)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SalaryRecord) error); ok {
		r0 = rf(salary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSalaryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSalaryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - salary *models.SalaryRecord
func (_e *MockSalaryRepository_Expecter) Update(salary interface{}) *MockSalaryRepository_Update_Call {
	return &MockSalaryRepository_Update_Call{Call: _e.mock.On("Update", salary)}
}

func (_c *MockSalaryRepository_Update_Call) Run(run func(salary *models.SalaryRecord)) *MockSalaryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.SalaryRecord))
	})
	return _c
}

func (_c *MockSalaryRepository_Update_Call) Return(_a0 error) *MockSalaryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSalaryRepository_Update_Call) RunAndReturn(run func(*models.SalaryRecord) error) *MockSalaryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSalaryRepository creates a new instance of MockSalaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSalaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSalaryRepository {
	mock := &MockSalaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
