// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockExpenseCategoryRepository is an autogenerated mock type for the ExpenseCategoryRepository type
type MockExpenseCategoryRepository struct {
	mock.Mock
}

type MockExpenseCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseCategoryRepository) EXPECT() *MockExpenseCategoryRepository_Expecter {
	return &MockExpenseCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: cat
func (_m *MockExpenseCategoryRepository) Create(cat *models.ExpenseCategory) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ExpenseCategory) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExpenseCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - cat *models.ExpenseCategory
func (_e *MockExpenseCategoryRepository_Expecter) Create(cat interface{}) *MockExpenseCategoryRepository_Create_Call {
	return &MockExpenseCategoryRepository_Create_Call{Call: _e.mock.On("Create", cat)}
}

func (_c *MockExpenseCategoryRepository_Create_Call) Run(run func(cat *models.ExpenseCategory)) *MockExpenseCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ExpenseCategory))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_Create_Call) Return(_a0 error) *MockExpenseCategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseCategoryRepository_Create_Call) RunAndReturn(run func(*models.ExpenseCategory) error) *MockExpenseCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockExpenseCategoryRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpenseCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockExpenseCategoryRepository_Expecter) Delete(id interface{}) *MockExpenseCategoryRepository_Delete_Call {
	return &MockExpenseCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockExpenseCategoryRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockExpenseCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_Delete_Call) Return(_a0 error) *MockExpenseCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseCategoryRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockExpenseCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockExpenseCategoryRepository) FindAll(offset int, limit int) ([]models.ExpenseCategory, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.ExpenseCategory
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.ExpenseCategory, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.ExpenseCategory); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockExpenseCategoryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockExpenseCategoryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockExpenseCategoryRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockExpenseCategoryRepository_FindAll_Call {
	return &MockExpenseCategoryRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockExpenseCategoryRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockExpenseCategoryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_FindAll_Call) Return(_a0 []models.ExpenseCategory, _a1 int64, _a2 error) *MockExpenseCategoryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockExpenseCategoryRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.ExpenseCategory, int64, error)) *MockExpenseCategoryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockExpenseCategoryRepository) FindByID(id uuid.UUID) (*models.ExpenseCategory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.ExpenseCategory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.ExpenseCategory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockExpenseCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockExpenseCategoryRepository_Expecter) FindByID(id interface{}) *MockExpenseCategoryRepository_FindByID_Call {
	return &MockExpenseCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockExpenseCategoryRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockExpenseCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_FindByID_Call) Return(_a0 *models.ExpenseCategory, _a1 error) *MockExpenseCategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseCategoryRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.ExpenseCategory, error)) *MockExpenseCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: cat
func (_m *MockExpenseCategoryRepository) Update(cat *models.ExpenseCategory) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ExpenseCategory) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpenseCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - cat *models.ExpenseCategory
func (_e *MockExpenseCategoryRepository_Expecter) Update(cat interface{}) *MockExpenseCategoryRepository_Update_Call {
	return &MockExpenseCategoryRepository_Update_Call{Call: _e.mock.On("Update", cat)}
}

func (_c *MockExpenseCategoryRepository_Update_Call) Run(run func(cat *models.ExpenseCategory)) *MockExpenseCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ExpenseCategory))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_Update_Call) Return(_a0 error) *MockExpenseCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseCategoryRepository_Update_Call) RunAndReturn(run func(*models.ExpenseCategory) error) *MockExpenseCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpenseCategoryRepository creates a new instance of MockExpenseCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseCategoryRepository {
	mock := &MockExpenseCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
