// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// MockAffiliateCommissionRepository is an autogenerated mock type for the AffiliateCommissionRepository type
type MockAffiliateCommissionRepository struct {
	mock.Mock
}

type MockAffiliateCommissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAffiliateCommissionRepository) EXPECT() *MockAffiliateCommissionRepository_Expecter {
	return &MockAffiliateCommissionRepository_Expecter{mock: &_m.Mock}
}

// CreateWithTx provides a mock function with given fields: tx, ac
func (_m *MockAffiliateCommissionRepository) CreateWithTx(tx *gorm.DB, ac *models.AffiliateCommission) error {
	ret := _m.Called(tx, ac)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.AffiliateCommission) error); ok {
		r0 = rf(tx, ac)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAffiliateCommissionRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockAffiliateCommissionRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - ac *models.AffiliateCommission
func (_e *MockAffiliateCommissionRepository_Expecter) CreateWithTx(tx interface{}, ac interface{}) *MockAffiliateCommissionRepository_CreateWithTx_Call {
	return &MockAffiliateCommissionRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", tx, ac)}
}

func (_c *MockAffiliateCommissionRepository_CreateWithTx_Call) Run(run func(tx *gorm.DB, ac *models.AffiliateCommission)) *MockAffiliateCommissionRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.AffiliateCommission))
	})
	return _c
}

func (_c *MockAffiliateCommissionRepository_CreateWithTx_Call) Return(_a0 error) *MockAffiliateCommissionRepository_CreateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAffiliateCommissionRepository_CreateWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.AffiliateCommission) error) *MockAffiliateCommissionRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAffiliateID provides a mock function with given fields: affiliateID, offset, limit
func (_m *MockAffiliateCommissionRepository) FindByAffiliateID(affiliateID uuid.UUID, offset int, limit int) ([]models.AffiliateCommission, int64, error) {
	ret := _m.Called(affiliateID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByAffiliateID")
	}

	var r0 []models.AffiliateCommission
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.AffiliateCommission, int64, error)); ok {
		return rf(affiliateID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.AffiliateCommission); ok {
		r0 = rf(affiliateID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AffiliateCommission)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(affiliateID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(affiliateID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAffiliateCommissionRepository_FindByAffiliateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAffiliateID'
type MockAffiliateCommissionRepository_FindByAffiliateID_Call struct {
	*mock.Call
}

// FindByAffiliateID is a helper method to define mock.On call
//   - affiliateID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockAffiliateCommissionRepository_Expecter) FindByAffiliateID(affiliateID interface{}, offset interface{}, limit interface{}) *MockAffiliateCommissionRepository_FindByAffiliateID_Call {
	return &MockAffiliateCommissionRepository_FindByAffiliateID_Call{Call: _e.mock.On("FindByAffiliateID", affiliateID, offset, limit)}
}

func (_c *MockAffiliateCommissionRepository_FindByAffiliateID_Call) Run(run func(affiliateID uuid.UUID, offset int, limit int)) *MockAffiliateCommissionRepository_FindByAffiliateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAffiliateCommissionRepository_FindByAffiliateID_Call) Return(_a0 []models.AffiliateCommission, _a1 int64, _a2 error) *MockAffiliateCommissionRepository_FindByAffiliateID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAffiliateCommissionRepository_FindByAffiliateID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.AffiliateCommission, int64, error)) *MockAffiliateCommissionRepository_FindByAffiliateID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAffiliateCommissionRepository creates a new instance of MockAffiliateCommissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAffiliateCommissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAffiliateCommissionRepository {
	mock := &MockAffiliateCommissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
