// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductCategoryRepository is an autogenerated mock type for the ProductCategoryRepository type
type MockProductCategoryRepository struct {
	mock.Mock
}

type MockProductCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductCategoryRepository) EXPECT() *MockProductCategoryRepository_Expecter {
	return &MockProductCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: cat
func (_m *MockProductCategoryRepository) Create(cat *models.ProductCategory) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ProductCategory) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - cat *models.ProductCategory
func (_e *MockProductCategoryRepository_Expecter) Create(cat interface{}) *MockProductCategoryRepository_Create_Call {
	return &MockProductCategoryRepository_Create_Call{Call: _e.mock.On("Create", cat)}
}

func (_c *MockProductCategoryRepository_Create_Call) Run(run func(cat *models.ProductCategory)) *MockProductCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ProductCategory))
	})
	return _c
}

func (_c *MockProductCategoryRepository_Create_Call) Return(_a0 error) *MockProductCategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductCategoryRepository_Create_Call) RunAndReturn(run func(*models.ProductCategory) error) *MockProductCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductCategoryRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductCategoryRepository_Expecter) Delete(id interface{}) *MockProductCategoryRepository_Delete_Call {
	return &MockProductCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductCategoryRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockProductCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductCategoryRepository_Delete_Call) Return(_a0 error) *MockProductCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductCategoryRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockProductCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockProductCategoryRepository) FindAll(offset int, limit int) ([]models.ProductCategory, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.ProductCategory
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.ProductCategory, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.ProductCategory); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProductCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductCategoryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockProductCategoryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockProductCategoryRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockProductCategoryRepository_FindAll_Call {
	return &MockProductCategoryRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockProductCategoryRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockProductCategoryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockProductCategoryRepository_FindAll_Call) Return(_a0 []models.ProductCategory, _a1 int64, _a2 error) *MockProductCategoryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductCategoryRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.ProductCategory, int64, error)) *MockProductCategoryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockProductCategoryRepository) FindByID(id uuid.UUID) (*models.ProductCategory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.ProductCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.ProductCategory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.ProductCategory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductCategoryRepository_Expecter) FindByID(id interface{}) *MockProductCategoryRepository_FindByID_Call {
	return &MockProductCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockProductCategoryRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockProductCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductCategoryRepository_FindByID_Call) Return(_a0 *models.ProductCategory, _a1 error) *MockProductCategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductCategoryRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.ProductCategory, error)) *MockProductCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: cat
func (_m *MockProductCategoryRepository) Update(cat *models.ProductCategory) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ProductCategory) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - cat *models.ProductCategory
func (_e *MockProductCategoryRepository_Expecter) Update(cat interface{}) *MockProductCategoryRepository_Update_Call {
	return &MockProductCategoryRepository_Update_Call{Call: _e.mock.On("Update", cat)}
}

func (_c *MockProductCategoryRepository_Update_Call) Run(run func(cat *models.ProductCategory)) *MockProductCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ProductCategory))
	})
	return _c
}

func (_c *MockProductCategoryRepository_Update_Call) Return(_a0 error) *MockProductCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductCategoryRepository_Update_Call) RunAndReturn(run func(*models.ProductCategory) error) *MockProductCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductCategoryRepository creates a new instance of MockProductCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductCategoryRepository {
	mock := &MockProductCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
