// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCashDrawerRepository is an autogenerated mock type for the CashDrawerRepository type
type MockCashDrawerRepository struct {
	mock.Mock
}

type MockCashDrawerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCashDrawerRepository) EXPECT() *MockCashDrawerRepository_Expecter {
	return &MockCashDrawerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: drawer
func (_m *MockCashDrawerRepository) Create(drawer *models.CashDrawer) error {
	ret := _m.Called(drawer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.CashDrawer) error); ok {
		r0 = rf(drawer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCashDrawerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCashDrawerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - drawer *models.CashDrawer
func (_e *MockCashDrawerRepository_Expecter) Create(drawer interface{}) *MockCashDrawerRepository_Create_Call {
	return &MockCashDrawerRepository_Create_Call{Call: _e.mock.On("Create", drawer)}
}

func (_c *MockCashDrawerRepository_Create_Call) Run(run func(drawer *models.CashDrawer)) *MockCashDrawerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CashDrawer))
	})
	return _c
}

func (_c *MockCashDrawerRepository_Create_Call) Return(_a0 error) *MockCashDrawerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCashDrawerRepository_Create_Call) RunAndReturn(run func(*models.CashDrawer) error) *MockCashDrawerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchID provides a mock function with given fields: branchID, offset, limit
func (_m *MockCashDrawerRepository) FindByBranchID(branchID uuid.UUID, offset int, limit int) ([]models.CashDrawer, int64, error) {
	ret := _m.Called(branchID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchID")
	}

	var r0 []models.CashDrawer
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.CashDrawer, int64, error)); ok {
		return rf(branchID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.CashDrawer); ok {
		r0 = rf(branchID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CashDrawer)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCashDrawerRepository_FindByBranchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchID'
type MockCashDrawerRepository_FindByBranchID_Call struct {
	*mock.Call
}

// FindByBranchID is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockCashDrawerRepository_Expecter) FindByBranchID(branchID interface{}, offset interface{}, limit interface{}) *MockCashDrawerRepository_FindByBranchID_Call {
	return &MockCashDrawerRepository_FindByBranchID_Call{Call: _e.mock.On("FindByBranchID", branchID, offset, limit)}
}

func (_c *MockCashDrawerRepository_FindByBranchID_Call) Run(run func(branchID uuid.UUID, offset int, limit int)) *MockCashDrawerRepository_FindByBranchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCashDrawerRepository_FindByBranchID_Call) Return(_a0 []models.CashDrawer, _a1 int64, _a2 error) *MockCashDrawerRepository_FindByBranchID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCashDrawerRepository_FindByBranchID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.CashDrawer, int64, error)) *MockCashDrawerRepository_FindByBranchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockCashDrawerRepository) FindByID(id uuid.UUID) (*models.CashDrawer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.CashDrawer
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.CashDrawer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.CashDrawer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CashDrawer)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCashDrawerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCashDrawerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCashDrawerRepository_Expecter) FindByID(id interface{}) *MockCashDrawerRepository_FindByID_Call {
	return &MockCashDrawerRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockCashDrawerRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockCashDrawerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockCashDrawerRepository_FindByID_Call) Return(_a0 *models.CashDrawer, _a1 error) *MockCashDrawerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCashDrawerRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.CashDrawer, error)) *MockCashDrawerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOpenByBranch provides a mock function with given fields: branchID
func (_m *MockCashDrawerRepository) FindOpenByBranch(branchID uuid.UUID) (*models.CashDrawer, error) {
	ret := _m.Called(branchID)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenByBranch")
	}

	var r0 *models.CashDrawer
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.CashDrawer, error)); ok {
		return rf(branchID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.CashDrawer); ok {
		r0 = rf(branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CashDrawer)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCashDrawerRepository_FindOpenByBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOpenByBranch'
type MockCashDrawerRepository_FindOpenByBranch_Call struct {
	*mock.Call
}

// FindOpenByBranch is a helper method to define mock.On call
//   - branchID uuid.UUID
func (_e *MockCashDrawerRepository_Expecter) FindOpenByBranch(branchID interface{}) *MockCashDrawerRepository_FindOpenByBranch_Call {
	return &MockCashDrawerRepository_FindOpenByBranch_Call{Call: _e.mock.On("FindOpenByBranch", branchID)}
}

func (_c *MockCashDrawerRepository_FindOpenByBranch_Call) Run(run func(branchID uuid.UUID)) *MockCashDrawerRepository_FindOpenByBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockCashDrawerRepository_FindOpenByBranch_Call) Return(_a0 *models.CashDrawer, _a1 error) *MockCashDrawerRepository_FindOpenByBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCashDrawerRepository_FindOpenByBranch_Call) RunAndReturn(run func(uuid.UUID) (*models.CashDrawer, error)) *MockCashDrawerRepository_FindOpenByBranch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: drawer
func (_m *MockCashDrawerRepository) Update(drawer *models.CashDrawer) error {
	ret := _m.Called(drawer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.CashDrawer) error); ok {
		r0 = rf(drawer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCashDrawerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCashDrawerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - drawer *models.CashDrawer
func (_e *MockCashDrawerRepository_Expecter) Update(drawer interface{}) *MockCashDrawerRepository_Update_Call {
	return &MockCashDrawerRepository_Update_Call{Call: _e.mock.On("Update", drawer)}
}

func (_c *MockCashDrawerRepository_Update_Call) Run(run func(drawer *models.CashDrawer)) *MockCashDrawerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CashDrawer))
	})
	return _c
}

func (_c *MockCashDrawerRepository_Update_Call) Return(_a0 error) *MockCashDrawerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCashDrawerRepository_Update_Call) RunAndReturn(run func(*models.CashDrawer) error) *MockCashDrawerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCashDrawerRepository creates a new instance of MockCashDrawerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCashDrawerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCashDrawerRepository {
	mock := &MockCashDrawerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
