// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBranchRepository is an autogenerated mock type for the BranchRepository type
type MockBranchRepository struct {
	mock.Mock
}

type MockBranchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBranchRepository) EXPECT() *MockBranchRepository_Expecter {
	return &MockBranchRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: branch
func (_m *MockBranchRepository) Create(branch *models.Branch) error {
	ret := _m.Called(branch)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Branch) error); ok {
		r0 = rf(branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBranchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - branch *models.Branch
func (_e *MockBranchRepository_Expecter) Create(branch interface{}) *MockBranchRepository_Create_Call {
	return &MockBranchRepository_Create_Call{Call: _e.mock.On("Create", branch)}
}

func (_c *MockBranchRepository_Create_Call) Run(run func(branch *models.Branch)) *MockBranchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Branch))
	})
	return _c
}

func (_c *MockBranchRepository_Create_Call) Return(_a0 error) *MockBranchRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchRepository_Create_Call) RunAndReturn(run func(*models.Branch) error) *MockBranchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockBranchRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBranchRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBranchRepository_Expecter) Delete(id interface{}) *MockBranchRepository_Delete_Call {
	return &MockBranchRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockBranchRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockBranchRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchRepository_Delete_Call) Return(_a0 error) *MockBranchRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockBranchRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockBranchRepository) FindAll(offset int, limit int) ([]models.Branch, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Branch
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Branch, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Branch); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBranchRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBranchRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockBranchRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockBranchRepository_FindAll_Call {
	return &MockBranchRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockBranchRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockBranchRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBranchRepository_FindAll_Call) Return(_a0 []models.Branch, _a1 int64, _a2 error) *MockBranchRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBranchRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.Branch, int64, error)) *MockBranchRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: code
func (_m *MockBranchRepository) FindByCode(code string) (*models.Branch, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Branch, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Branch); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockBranchRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - code string
func (_e *MockBranchRepository_Expecter) FindByCode(code interface{}) *MockBranchRepository_FindByCode_Call {
	return &MockBranchRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", code)}
}

func (_c *MockBranchRepository_FindByCode_Call) Run(run func(code string)) *MockBranchRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBranchRepository_FindByCode_Call) Return(_a0 *models.Branch, _a1 error) *MockBranchRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchRepository_FindByCode_Call) RunAndReturn(run func(string) (*models.Branch, error)) *MockBranchRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockBranchRepository) FindByID(id uuid.UUID) (*models.Branch, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Branch, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Branch); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBranchRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBranchRepository_Expecter) FindByID(id interface{}) *MockBranchRepository_FindByID_Call {
	return &MockBranchRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockBranchRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockBranchRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchRepository_FindByID_Call) Return(_a0 *models.Branch, _a1 error) *MockBranchRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Branch, error)) *MockBranchRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: branch
func (_m *MockBranchRepository) Update(branch *models.Branch) error {
	ret := _m.Called(branch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Branch) error); ok {
		r0 = rf(branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBranchRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - branch *models.Branch
func (_e *MockBranchRepository_Expecter) Update(branch interface{}) *MockBranchRepository_Update_Call {
	return &MockBranchRepository_Update_Call{Call: _e.mock.On("Update", branch)}
}

func (_c *MockBranchRepository_Update_Call) Run(run func(branch *models.Branch)) *MockBranchRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Branch))
	})
	return _c
}

func (_c *MockBranchRepository_Update_Call) Return(_a0 error) *MockBranchRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchRepository_Update_Call) RunAndReturn(run func(*models.Branch) error) *MockBranchRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBranchRepository creates a new instance of MockBranchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBranchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBranchRepository {
	mock := &MockBranchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
