// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAffiliateRepository is an autogenerated mock type for the AffiliateRepository type
type MockAffiliateRepository struct {
	mock.Mock
}

type MockAffiliateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAffiliateRepository) EXPECT() *MockAffiliateRepository_Expecter {
	return &MockAffiliateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: affiliate
func (_m *MockAffiliateRepository) Create(affiliate *models.Affiliate) error {
	ret := _m.Called(affiliate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Affiliate) error); ok {
		r0 = rf(affiliate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAffiliateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAffiliateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - affiliate *models.Affiliate
func (_e *MockAffiliateRepository_Expecter) Create(affiliate interface{}) *MockAffiliateRepository_Create_Call {
	return &MockAffiliateRepository_Create_Call{Call: _e.mock.On("Create", affiliate)}
}

func (_c *MockAffiliateRepository_Create_Call) Run(run func(affiliate *models.Affiliate)) *MockAffiliateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Affiliate))
	})
	return _c
}

func (_c *MockAffiliateRepository_Create_Call) Return(_a0 error) *MockAffiliateRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAffiliateRepository_Create_Call) RunAndReturn(run func(*models.Affiliate) error) *MockAffiliateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockAffiliateRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAffiliateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAffiliateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockAffiliateRepository_Expecter) Delete(id interface{}) *MockAffiliateRepository_Delete_Call {
	return &MockAffiliateRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockAffiliateRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockAffiliateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockAffiliateRepository_Delete_Call) Return(_a0 error) *MockAffiliateRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAffiliateRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockAffiliateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockAffiliateRepository) FindAll(offset int, limit int) ([]models.Affiliate, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Affiliate
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Affiliate, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Affiliate); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Affiliate)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAffiliateRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockAffiliateRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockAffiliateRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockAffiliateRepository_FindAll_Call {
	return &MockAffiliateRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockAffiliateRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockAffiliateRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockAffiliateRepository_FindAll_Call) Return(_a0 []models.Affiliate, _a1 int64, _a2 error) *MockAffiliateRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAffiliateRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.Affiliate, int64, error)) *MockAffiliateRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: code
func (_m *MockAffiliateRepository) FindByCode(code string) (*models.Affiliate, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Affiliate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Affiliate, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Affiliate); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Affiliate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAffiliateRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockAffiliateRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - code string
func (_e *MockAffiliateRepository_Expecter) FindByCode(code interface{}) *MockAffiliateRepository_FindByCode_Call {
	return &MockAffiliateRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", code)}
}

func (_c *MockAffiliateRepository_FindByCode_Call) Run(run func(code string)) *MockAffiliateRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAffiliateRepository_FindByCode_Call) Return(_a0 *models.Affiliate, _a1 error) *MockAffiliateRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAffiliateRepository_FindByCode_Call) RunAndReturn(run func(string) (*models.Affiliate, error)) *MockAffiliateRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockAffiliateRepository) FindByID(id uuid.UUID) (*models.Affiliate, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Affiliate
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Affiliate, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Affiliate); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Affiliate)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAffiliateRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAffiliateRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockAffiliateRepository_Expecter) FindByID(id interface{}) *MockAffiliateRepository_FindByID_Call {
	return &MockAffiliateRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockAffiliateRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockAffiliateRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockAffiliateRepository_FindByID_Call) Return(_a0 *models.Affiliate, _a1 error) *MockAffiliateRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAffiliateRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Affiliate, error)) *MockAffiliateRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: affiliate
func (_m *MockAffiliateRepository) Update(affiliate *models.Affiliate) error {
	ret := _m.Called(affiliate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Affiliate) error); ok {
		r0 = rf(affiliate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAffiliateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAffiliateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - affiliate *models.Affiliate
func (_e *MockAffiliateRepository_Expecter) Update(affiliate interface{}) *MockAffiliateRepository_Update_Call {
	return &MockAffiliateRepository_Update_Call{Call: _e.mock.On("Update", affiliate)}
}

func (_c *MockAffiliateRepository_Update_Call) Run(run func(affiliate *models.Affiliate)) *MockAffiliateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Affiliate))
	})
	return _c
}

func (_c *MockAffiliateRepository_Update_Call) Return(_a0 error) *MockAffiliateRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAffiliateRepository_Update_Call) RunAndReturn(run func(*models.Affiliate) error) *MockAffiliateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAffiliateRepository creates a new instance of MockAffiliateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAffiliateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAffiliateRepository {
	mock := &MockAffiliateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
