// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type MockExpenseRepository struct {
	mock.Mock
}

type MockExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseRepository) EXPECT() *MockExpenseRepository_Expecter {
	return &MockExpenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: expense
func (_m *MockExpenseRepository) Create(expense *models.Expense) error {
	ret := _m.Called(expense)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Expense) error); ok {
		r0 = rf(expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExpenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - expense *models.Expense
func (_e *MockExpenseRepository_Expecter) Create(expense interface{}) *MockExpenseRepository_Create_Call {
	return &MockExpenseRepository_Create_Call{Call: _e.mock.On("Create", expense)}
}

func (_c *MockExpenseRepository_Create_Call) Run(run func(expense *models.Expense)) *MockExpenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Expense))
	})
	return _c
}

func (_c *MockExpenseRepository_Create_Call) Return(_a0 error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Create_Call) RunAndReturn(run func(*models.Expense) error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockExpenseRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockExpenseRepository_Expecter) Delete(id interface{}) *MockExpenseRepository_Delete_Call {
	return &MockExpenseRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockExpenseRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockExpenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) Return(_a0 error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchID provides a mock function with given fields: branchID, offset, limit
func (_m *MockExpenseRepository) FindByBranchID(branchID uuid.UUID, offset int, limit int) ([]models.Expense, int64, error) {
	ret := _m.Called(branchID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchID")
	}

	var r0 []models.Expense
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.Expense, int64, error)); ok {
		return rf(branchID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.Expense); ok {
		r0 = rf(branchID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockExpenseRepository_FindByBranchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchID'
type MockExpenseRepository_FindByBranchID_Call struct {
	*mock.Call
}

// FindByBranchID is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockExpenseRepository_Expecter) FindByBranchID(branchID interface{}, offset interface{}, limit interface{}) *MockExpenseRepository_FindByBranchID_Call {
	return &MockExpenseRepository_FindByBranchID_Call{Call: _e.mock.On("FindByBranchID", branchID, offset, limit)}
}

func (_c *MockExpenseRepository_FindByBranchID_Call) Run(run func(branchID uuid.UUID, offset int, limit int)) *MockExpenseRepository_FindByBranchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockExpenseRepository_FindByBranchID_Call) Return(_a0 []models.Expense, _a1 int64, _a2 error) *MockExpenseRepository_FindByBranchID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockExpenseRepository_FindByBranchID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.Expense, int64, error)) *MockExpenseRepository_FindByBranchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockExpenseRepository) FindByID(id uuid.UUID) (*models.Expense, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Expense, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Expense); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockExpenseRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockExpenseRepository_Expecter) FindByID(id interface{}) *MockExpenseRepository_FindByID_Call {
	return &MockExpenseRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockExpenseRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockExpenseRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpenseRepository_FindByID_Call) Return(_a0 *models.Expense, _a1 error) *MockExpenseRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Expense, error)) *MockExpenseRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// SumByBranchAndDateRange provides a mock function with given fields: branchID, start, end
func (_m *MockExpenseRepository) SumByBranchAndDateRange(branchID uuid.UUID, start time.Time, end time.Time) (int64, error) {
	ret := _m.Called(branchID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for SumByBranchAndDateRange")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return rf(branchID, start, end)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(branchID, start, end)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(branchID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_SumByBranchAndDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByBranchAndDateRange'
type MockExpenseRepository_SumByBranchAndDateRange_Call struct {
	*mock.Call
}

// SumByBranchAndDateRange is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - start time.Time
//   - end time.Time
func (_e *MockExpenseRepository_Expecter) SumByBranchAndDateRange(branchID interface{}, start interface{}, end interface{}) *MockExpenseRepository_SumByBranchAndDateRange_Call {
	return &MockExpenseRepository_SumByBranchAndDateRange_Call{Call: _e.mock.On("SumByBranchAndDateRange", branchID, start, end)}
}

func (_c *MockExpenseRepository_SumByBranchAndDateRange_Call) Run(run func(branchID uuid.UUID, start time.Time, end time.Time)) *MockExpenseRepository_SumByBranchAndDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockExpenseRepository_SumByBranchAndDateRange_Call) Return(_a0 int64, _a1 error) *MockExpenseRepository_SumByBranchAndDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_SumByBranchAndDateRange_Call) RunAndReturn(run func(uuid.UUID, time.Time, time.Time) (int64, error)) *MockExpenseRepository_SumByBranchAndDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: expense
func (_m *MockExpenseRepository) Update(expense *models.Expense) error {
	ret := _m.Called(expense)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Expense) error); ok {
		r0 = rf(expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - expense *models.Expense
func (_e *MockExpenseRepository_Expecter) Update(expense interface{}) *MockExpenseRepository_Update_Call {
	return &MockExpenseRepository_Update_Call{Call: _e.mock.On("Update", expense)}
}

func (_c *MockExpenseRepository_Update_Call) Run(run func(expense *models.Expense)) *MockExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Expense))
	})
	return _c
}

func (_c *MockExpenseRepository_Update_Call) Return(_a0 error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Update_Call) RunAndReturn(run func(*models.Expense) error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpenseRepository creates a new instance of MockExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseRepository {
	mock := &MockExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
