// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBranchStylistRepository is an autogenerated mock type for the BranchStylistRepository type
type MockBranchStylistRepository struct {
	mock.Mock
}

type MockBranchStylistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBranchStylistRepository) EXPECT() *MockBranchStylistRepository_Expecter {
	return &MockBranchStylistRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: bs
func (_m *MockBranchStylistRepository) Create(bs *models.BranchStylist) error {
	ret := _m.Called(bs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BranchStylist) error); ok {
		r0 = rf(bs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchStylistRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBranchStylistRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - bs *models.BranchStylist
func (_e *MockBranchStylistRepository_Expecter) Create(bs interface{}) *MockBranchStylistRepository_Create_Call {
	return &MockBranchStylistRepository_Create_Call{Call: _e.mock.On("Create", bs)}
}

func (_c *MockBranchStylistRepository_Create_Call) Run(run func(bs *models.BranchStylist)) *MockBranchStylistRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.BranchStylist))
	})
	return _c
}

func (_c *MockBranchStylistRepository_Create_Call) Return(_a0 error) *MockBranchStylistRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchStylistRepository_Create_Call) RunAndReturn(run func(*models.BranchStylist) error) *MockBranchStylistRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockBranchStylistRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchStylistRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBranchStylistRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBranchStylistRepository_Expecter) Delete(id interface{}) *MockBranchStylistRepository_Delete_Call {
	return &MockBranchStylistRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockBranchStylistRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockBranchStylistRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchStylistRepository_Delete_Call) Return(_a0 error) *MockBranchStylistRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchStylistRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockBranchStylistRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchAndStylist provides a mock function with given fields: branchID, stylistID
func (_m *MockBranchStylistRepository) FindByBranchAndStylist(branchID uuid.UUID, stylistID uuid.UUID) (*models.BranchStylist, error) {
	ret := _m.Called(branchID, stylistID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchAndStylist")
	}

	var r0 *models.BranchStylist
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.BranchStylist, error)); ok {
		return rf(branchID, stylistID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.BranchStylist); ok {
		r0 = rf(branchID, stylistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BranchStylist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(branchID, stylistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchStylistRepository_FindByBranchAndStylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchAndStylist'
type MockBranchStylistRepository_FindByBranchAndStylist_Call struct {
	*mock.Call
}

// FindByBranchAndStylist is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - stylistID uuid.UUID
func (_e *MockBranchStylistRepository_Expecter) FindByBranchAndStylist(branchID interface{}, stylistID interface{}) *MockBranchStylistRepository_FindByBranchAndStylist_Call {
	return &MockBranchStylistRepository_FindByBranchAndStylist_Call{Call: _e.mock.On("FindByBranchAndStylist", branchID, stylistID)}
}

func (_c *MockBranchStylistRepository_FindByBranchAndStylist_Call) Run(run func(branchID uuid.UUID, stylistID uuid.UUID)) *MockBranchStylistRepository_FindByBranchAndStylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchStylistRepository_FindByBranchAndStylist_Call) Return(_a0 *models.BranchStylist, _a1 error) *MockBranchStylistRepository_FindByBranchAndStylist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchStylistRepository_FindByBranchAndStylist_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*models.BranchStylist, error)) *MockBranchStylistRepository_FindByBranchAndStylist_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBranchID provides a mock function with given fields: branchID, offset, limit
func (_m *MockBranchStylistRepository) FindByBranchID(branchID uuid.UUID, offset int, limit int) ([]models.BranchStylist, int64, error) {
	ret := _m.Called(branchID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByBranchID")
	}

	var r0 []models.BranchStylist
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]models.BranchStylist, int64, error)); ok {
		return rf(branchID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []models.BranchStylist); ok {
		r0 = rf(branchID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BranchStylist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) int64); ok {
		r1 = rf(branchID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int) error); ok {
		r2 = rf(branchID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBranchStylistRepository_FindByBranchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBranchID'
type MockBranchStylistRepository_FindByBranchID_Call struct {
	*mock.Call
}

// FindByBranchID is a helper method to define mock.On call
//   - branchID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockBranchStylistRepository_Expecter) FindByBranchID(branchID interface{}, offset interface{}, limit interface{}) *MockBranchStylistRepository_FindByBranchID_Call {
	return &MockBranchStylistRepository_FindByBranchID_Call{Call: _e.mock.On("FindByBranchID", branchID, offset, limit)}
}

func (_c *MockBranchStylistRepository_FindByBranchID_Call) Run(run func(branchID uuid.UUID, offset int, limit int)) *MockBranchStylistRepository_FindByBranchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockBranchStylistRepository_FindByBranchID_Call) Return(_a0 []models.BranchStylist, _a1 int64, _a2 error) *MockBranchStylistRepository_FindByBranchID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBranchStylistRepository_FindByBranchID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]models.BranchStylist, int64, error)) *MockBranchStylistRepository_FindByBranchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockBranchStylistRepository) FindByID(id uuid.UUID) (*models.BranchStylist, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.BranchStylist
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.BranchStylist, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.BranchStylist); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BranchStylist)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchStylistRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBranchStylistRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockBranchStylistRepository_Expecter) FindByID(id interface{}) *MockBranchStylistRepository_FindByID_Call {
	return &MockBranchStylistRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockBranchStylistRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockBranchStylistRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockBranchStylistRepository_FindByID_Call) Return(_a0 *models.BranchStylist, _a1 error) *MockBranchStylistRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchStylistRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.BranchStylist, error)) *MockBranchStylistRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: bs
func (_m *MockBranchStylistRepository) Update(bs *models.BranchStylist) error {
	ret := _m.Called(bs)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BranchStylist) error); ok {
		r0 = rf(bs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchStylistRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBranchStylistRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - bs *models.BranchStylist
func (_e *MockBranchStylistRepository_Expecter) Update(bs interface{}) *MockBranchStylistRepository_Update_Call {
	return &MockBranchStylistRepository_Update_Call{Call: _e.mock.On("Update", bs)}
}

func (_c *MockBranchStylistRepository_Update_Call) Run(run func(bs *models.BranchStylist)) *MockBranchStylistRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.BranchStylist))
	})
	return _c
}

func (_c *MockBranchStylistRepository_Update_Call) Return(_a0 error) *MockBranchStylistRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchStylistRepository_Update_Call) RunAndReturn(run func(*models.BranchStylist) error) *MockBranchStylistRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBranchStylistRepository creates a new instance of MockBranchStylistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBranchStylistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBranchStylistRepository {
	mock := &MockBranchStylistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
