// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: customer
func (_m *MockCustomerRepository) Create(customer *models.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCustomerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - customer *models.Customer
func (_e *MockCustomerRepository_Expecter) Create(customer interface{}) *MockCustomerRepository_Create_Call {
	return &MockCustomerRepository_Create_Call{Call: _e.mock.On("Create", customer)}
}

func (_c *MockCustomerRepository_Create_Call) Run(run func(customer *models.Customer)) *MockCustomerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Customer))
	})
	return _c
}

func (_c *MockCustomerRepository_Create_Call) Return(_a0 error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Create_Call) RunAndReturn(run func(*models.Customer) error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockCustomerRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCustomerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCustomerRepository_Expecter) Delete(id interface{}) *MockCustomerRepository_Delete_Call {
	return &MockCustomerRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCustomerRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockCustomerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) Return(_a0 error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockCustomerRepository) FindAll(offset int, limit int) ([]models.Customer, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Customer
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Customer, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Customer); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCustomerRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCustomerRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockCustomerRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockCustomerRepository_FindAll_Call {
	return &MockCustomerRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockCustomerRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockCustomerRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockCustomerRepository_FindAll_Call) Return(_a0 []models.Customer, _a1 int64, _a2 error) *MockCustomerRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCustomerRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.Customer, int64, error)) *MockCustomerRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockCustomerRepository) FindByID(id uuid.UUID) (*models.Customer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Customer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCustomerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCustomerRepository_Expecter) FindByID(id interface{}) *MockCustomerRepository_FindByID_Call {
	return &MockCustomerRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockCustomerRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockCustomerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockCustomerRepository_FindByID_Call) Return(_a0 *models.Customer, _a1 error) *MockCustomerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Customer, error)) *MockCustomerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: customer
func (_m *MockCustomerRepository) Update(customer *models.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCustomerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - customer *models.Customer
func (_e *MockCustomerRepository_Expecter) Update(customer interface{}) *MockCustomerRepository_Update_Call {
	return &MockCustomerRepository_Update_Call{Call: _e.mock.On("Update", customer)}
}

func (_c *MockCustomerRepository_Update_Call) Run(run func(customer *models.Customer)) *MockCustomerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Customer))
	})
	return _c
}

func (_c *MockCustomerRepository_Update_Call) Return(_a0 error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Update_Call) RunAndReturn(run func(*models.Customer) error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
