// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repositories

import (
	models "hairhaus-pos-be/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: log
func (_m *MockAuditLogRepository) Create(log *models.AuditLog) error {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AuditLog) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - log *models.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(log interface{}) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", log)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(log *models.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.AuditLog))
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(_a0 error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(*models.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function with given fields: tx, log
func (_m *MockAuditLogRepository) CreateWithTx(tx *gorm.DB, log *models.AuditLog) error {
	ret := _m.Called(tx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.AuditLog) error); ok {
		r0 = rf(tx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockAuditLogRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - log *models.AuditLog
func (_e *MockAuditLogRepository_Expecter) CreateWithTx(tx interface{}, log interface{}) *MockAuditLogRepository_CreateWithTx_Call {
	return &MockAuditLogRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", tx, log)}
}

func (_c *MockAuditLogRepository_CreateWithTx_Call) Run(run func(tx *gorm.DB, log *models.AuditLog)) *MockAuditLogRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.AuditLog))
	})
	return _c
}

func (_c *MockAuditLogRepository_CreateWithTx_Call) Return(_a0 error) *MockAuditLogRepository_CreateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogRepository_CreateWithTx_Call) RunAndReturn(run func(*gorm.DB, *models.AuditLog) error) *MockAuditLogRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: offset, limit
func (_m *MockAuditLogRepository) FindAll(offset int, limit int) ([]models.AuditLog, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.AuditLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.AuditLog, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.AuditLog); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuditLogRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockAuditLogRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockAuditLogRepository_Expecter) FindAll(offset interface{}, limit interface{}) *MockAuditLogRepository_FindAll_Call {
	return &MockAuditLogRepository_FindAll_Call{Call: _e.mock.On("FindAll", offset, limit)}
}

func (_c *MockAuditLogRepository_FindAll_Call) Run(run func(offset int, limit int)) *MockAuditLogRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockAuditLogRepository_FindAll_Call) Return(_a0 []models.AuditLog, _a1 int64, _a2 error) *MockAuditLogRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuditLogRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]models.AuditLog, int64, error)) *MockAuditLogRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEntity provides a mock function with given fields: entityType, entityID
func (_m *MockAuditLogRepository) FindByEntity(entityType string, entityID uuid.UUID) ([]models.AuditLog, error) {
	ret := _m.Called(entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for FindByEntity")
	}

	var r0 []models.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) ([]models.AuditLog, error)); ok {
		return rf(entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) []models.AuditLog); ok {
		r0 = rf(entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = rf(entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuditLogRepository_FindByEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEntity'
type MockAuditLogRepository_FindByEntity_Call struct {
	*mock.Call
}

// FindByEntity is a helper method to define mock.On call
//   - entityType string
//   - entityID uuid.UUID
func (_e *MockAuditLogRepository_Expecter) FindByEntity(entityType interface{}, entityID interface{}) *MockAuditLogRepository_FindByEntity_Call {
	return &MockAuditLogRepository_FindByEntity_Call{Call: _e.mock.On("FindByEntity", entityType, entityID)}
}

func (_c *MockAuditLogRepository_FindByEntity_Call) Run(run func(entityType string, entityID uuid.UUID)) *MockAuditLogRepository_FindByEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuditLogRepository_FindByEntity_Call) Return(_a0 []models.AuditLog, _a1 error) *MockAuditLogRepository_FindByEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuditLogRepository_FindByEntity_Call) RunAndReturn(run func(string, uuid.UUID) ([]models.AuditLog, error)) *MockAuditLogRepository_FindByEntity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
